### ISSUE TITLE
README - package version in static file config example is wrong 

### ISSUE THREAD

**Issue by mobileskyfi** [traefik/plugindemowasm#4]
But in the `README.md`, it shows the package version as `v0.2.1`.  However, as it exists in this repo, the only [release is v0.0.1](https://github.com/traefik/plugindemowasm/releases).  

The text shown is:
```
experimental:
  plugins:
    example:
      moduleName: github.com/traefik/plugindemowasm
      version: v0.2.1
```

Now it does load if you the version in _this_ repo:
```
experimental:
  plugins:
    example:
      moduleName: github.com/traefik/plugindemowasm
      version: v0.0.1
```
