### ISSUE TITLE
Loading WASM plugin using http-wasm without Go?

### ISSUE THREAD

**Issue by mobileskyfi** [traefik/plugindemowasm#6]
Not sure where to file this.  

Just for fun, I've been tried building Traefik WASM plugin using [Grain](https://grain-lang.org/).  I'm still working on the http-wasm binding and type-mapping, but it loads/runs as Grain-based WASM plugin from`/pluginsLocal/src/grain/plugin.wasm`.  

While not ready to publish anything on the Traefik Plugin Catalog, I did add the "traefik-plugin" GitHub tag to this project: https://github.com/tikoci/traefik-wasm-grain with following `.traefik.yml`:
```
displayName: traefik-wasm-grain
type: middleware
runtime: wasm
iconPath: icon.png
summary: Experimental plugin using WASM and grain-lang.org, directly using http-wasm ABI
testData:
  Headers:
    Foo: Bar
```

And docs suggest I should have gotten an automated #3 "Plugin Analyzer ... problem" bug reports by virtue of the tag.  But that never happened.  I even added a tagged release to project – just to trigger something – since I'm not 100% the .traefik.yml is right.  

Perhaps the "Plugin Catalog" also check to project type is "Go" – since GitHub flags tikoci/traefik-wasm-grain as a  `Makefile` project?
<img width="347" alt="image" src="https://github.com/traefik/plugindemowasm/assets/45924209/1e8d6707-e9cb-4af6-b183-e3891a47204d">

Not urgent here.  But be nice to know something _could_ be published to avoid file copies/Dockerfile-mod/etc to "localPlugins".
